export const ACTION_TYPES = {
  CREATE_IT_SCHOOL: "CREATE_IT_SCHOOL",
  UPDATE_IT_SCHOOL: "UPDATE_IT_SCHOOL",
  REGISTER_COURSE: "REGISTER_COURSE",
  START_LEARNING_GROUP: "START_LEARNING_GROUP",
  PASS_LESSON: "PASS_LESSON",
  END_LEARNING_GROUP: "END_LEARNING_GROUP",
};
